export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <nav className="bg-grey-300 w-screen grid grid-flow-row">Nav</nav>
      <body>{children}</body>
    </html>
  )
}
